spring:
  application:
    name: orders
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: false
  show-actuator: false
